kind = "mobile"
previewPath = "/nexuscast-mobile/"
title = "NexusCast Mobile"
version = "1.0.0"
id = "artifacts/nexuscast-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/nexuscast-mobile/" ]
localPort = 18940

[services.development]
run = "pnpm --filter @workspace/nexuscast-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nexuscast-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/nexuscast-mobile", "run", "serve" ]

[services.env]
PORT = "18940"
BASE_PATH = "/nexuscast-mobile/"
