const colors = {
  light: {
    text: "#e8f0ff",
    tint: "#00d4ff",
    background: "#0a0e27",
    foreground: "#e8f0ff",
    card: "#1a1f4f",
    cardForeground: "#e8f0ff",
    primary: "#00d4ff",
    primaryForeground: "#0a0e27",
    secondary: "#1a1f4f",
    secondaryForeground: "#e8f0ff",
    muted: "#1a1f4f",
    mutedForeground: "#a0b0d0",
    accent: "#0099ff",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#004d7f",
    input: "#1a1f4f",
    live: "#ff3b3b",
    success: "#22c55e",
  },
  dark: {
    text: "#e8f0ff",
    tint: "#00d4ff",
    background: "#0a0e27",
    foreground: "#e8f0ff",
    card: "#1a1f4f",
    cardForeground: "#e8f0ff",
    primary: "#00d4ff",
    primaryForeground: "#0a0e27",
    secondary: "#1a1f4f",
    secondaryForeground: "#e8f0ff",
    muted: "#1a1f4f",
    mutedForeground: "#a0b0d0",
    accent: "#0099ff",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#004d7f",
    input: "#1a1f4f",
    live: "#ff3b3b",
    success: "#22c55e",
  },
  radius: 12,
};

export default colors;
